---
- name: Playbook for learning to troubleshoot...can you find/fix the errors?
  hosts: Greg-rocky9
  gather_facts: false
  vars: 
  tasks:
    - name: Collect sudoers file contents
      ansible.builtin.shell: cat /etc/sudoers 
      register: sudoers_collect
      become: true
      changed_when: false

    - name: Display collected variable info
      ansible.builtin.debug:
        # msg: "My sudo file users {{ sudoers_collect.stdout_lines }}"
        var: sudoers_collect.stdout_lines