---
- name: Playbook for learning to troubleshoot...can you find/fix the errors?
  hosts: TestHost1
  gather_facts: false
  vars:
  tasks:
    - name: Collect sudoers file contents
      ansible.builtin.shell: cat /etc/sudoers
      register: sudoers-collect

    - name: Display collected variable info
      ansible.builtin.dedug:
      msg: My sudo file users "{{ sudoers_collect.stdout_lines }}"